name: Run Postman Collection

on:
 push:
    branches:
    - master

jobs:
 api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - name: Install Newman
      run: npm install -g newman

    - name: Install newman dependencies
      run: npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: newman run postman/placeholder.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: postman-test-report
        path: report.html
